# Generated by Django 6.0.6 on 2026-07-02 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('sports', '0002_terrain_slot_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_reservation_per_timeslot',
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('timeslot',), name='unique_confirmed_reservation_per_timeslot'),
        ),
    ]
