# Generated by Django 6.0.6 on 2026-09-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=20, verbose_name='numéro de téléphone'),
            preserve_default=False,
        ),
    ]
