# Generated by Django 6.0.6 on 2026-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classe',
            field=models.CharField(blank=True, max_length=100, verbose_name='classe'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='photo de profil'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, verbose_name='spécialité'),
        ),
    ]
