# Generated by Django 6.0.6 on 2026-09-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_is_deactivated_user_is_suspended_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Warning',
        ),
    ]
