# Generated by Django 6.0.6 on 2026-09-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('invited', 'Invited to a game'), ('kicked', 'Kicked from a game'), ('game_cancelled', 'Game cancelled'), ('invite_accepted', 'Invitation accepted'), ('invite_declined', 'Invitation declined'), ('member_left', 'Member left the game'), ('member_joined', 'Member joined the game'), ('booking_created', 'Booking created (admin)'), ('booking_cancelled', 'Booking cancelled (admin)'), ('warning', 'Conduct warning')], max_length=32),
        ),
    ]
