# Generated by Django 6.0.6 on 2026-09-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.PositiveIntegerField(default=100, help_text="Chosen by the owner at booking time, capped by the terrain's max capacity.", verbose_name='taille du lobby'),
            preserve_default=False,
        ),
    ]
