# Generated by Django 6.0.6 on 2026-07-01 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='sports/icons/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='terrains/photos/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrains', to='sports.sport')),
            ],
        ),
    ]
