# Generated by Django 6.0.6 on 2026-07-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='slot_duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration of each bookable slot in minutes'),
        ),
    ]
