# Generated by Django 6.0.6 on 2026-08-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_terrain_slot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='terrains/'),
        ),
    ]
